// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttemptReconnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttemptReconnect'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTradeHistory() {
  return window['go']['main']['App']['GetTradeHistory']();
}
