// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttemptReconnect(arg1:boolean,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTradeHistory():Promise<Array<main.Trade>>;
